service: test-app
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:ap-northeast-1:000000000000:table/MonthlyPaymentBatchResults
        - Effect: Allow
          Action:
            - states:StartExecution
          Resource:
            - "arn:aws:states:ap-northeast-1:000000000000:stateMachine:PaymentBatchStateMachine"
functions:
  getPaymentTargetUsers:
    handler: handlers/getPaymentTargetUsers.handler
  sendPaymentRequest:
    handler: handlers/sendPaymentRequest.handler
  saveBatchResult:
    handler: handlers/saveBatchResult.handler
  paymentMockServer:
    handler: handlers/paymentMockServer.handler
    events:
      - http:
          path: api/v1/payments
          method: post
stepFunctions:
  stateMachines:
    paymentBatch:
      name: PaymentBatchStateMachine
      definition:
        StartAt: getPaymentTargetUsers
        States:
          getPaymentTargetUsers:
            Type: Task
            Resource:
              Fn::GetAtt: [getPaymentTargetUsers, Arn]
            Next: ProcessPaymentTargetUsers
          ProcessPaymentTargetUsers:
            Type: Map
            ItemsPath: "$.users"
            Iterator:
              StartAt: SendPaymentRequest
              States:
                SendPaymentRequest:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [sendPaymentRequest, Arn]
                  Catch:
                    - ErrorEquals: ["States.ALL"]
                      Next: Error
                  Next: Success
                Success:
                  Type: Pass
                  Result: { "status": "success" }
                  End: true
                Error:
                  Type: Pass
                  Result: { "status": "error" }
                  End: true
            Next: SaveBatchResult
          SaveBatchResult:
            Type: Task
            Resource:
              Fn::GetAtt: [saveBatchResult, Arn]
            Next: Finished
          Finished:
            Type: Succeed
resources:
  Resources:
    MonthlyPaymentBatchResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MonthlyPaymentBatchResults
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
plugins:
  - serverless-step-functions
