service: test-app

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

functions:
  mockApi:
    handler: handlers/paymentMockServer.handler
    events:
      - http:
          path: api/v1/payments
          method: post
  batchApiRequest:
    handler: handlers/billingBatch.handler
    timeout: 900
